### PR TITLE
Ticket 60 - Upcoming events section

### PR DESCRIPTION
**Pull request by christerresin**
Add section on main page
Render 4 events/movies with image, date and title
Add an upcoming movie to db
Styling rules

Fetch, checkout and see if you can see section on index

### CODE REVIEW

**Review by TheAzne — APPROVED** [review]
Allright!

**Comment by christerresin** [comment]
package.json conflict, removed webpack and added sass as watch

**Comment by Erm0es** [comment]
*is events the same as movies?
*"best practice -  Add functionality with JavaScript, don’t create too much content"

Ser snyggt ut och korrekt utifrån whimsical!

**Review by amyrman — APPROVED** [review]
Tested Acceptance criteria, works like a charm! Good job, mate! Approved.

**Pull request merged**
